lang:
  - en-us
  - zh-cn
  - zh-tw

path: ../assets/gvlk.json

win:
  - 'windows-vista'
  - 'windows-7'
  - 'windows-8'
  - 'windows-81'
  - 'windows-11-and-windows-10-semi-annual-channel-versions'
  - 'windows-10-ltsb-2015'
  - 'windows-10-ltsb-2016'
  - 'windows-10-ltsc-2021-and-2019'

win-server:
  - 'windows-server-version-1709'
  - 'windows-server-version-1803'
  - 'windows-server-versions-20h2-2004-1909-1903-and-1809'
  - 'windows-server-2016'
  - 'windows-server-2019'
  - 'windows-server-2022'
  - 'windows-server-2012-r2'
  - 'windows-server-2012'
  - 'windows-server-2008-r2'
  - 'windows-server-2008'
